TRANSLATE='gpu'
NUM_GPUS=1

INPUT_WORD_DROPOUT_RATE=0.2
TARGET_WORD_DROPOUT_RATE=0.1
EDIT_WEIGHT=3

MODEL=transformer
MODEL_TYPE=transformer_base_single_gpu

EXPERIMENT_ROOT_DIR=/home/user/ # TODO set it yourself

PROBLEM=artificial_errors
PROBLEM_DIR=$EXPERIMENT_ROOT_DIR/problems/
TRAIN_DIR=$EXPERIMENT_ROOT_DIR/t2t_train # path to root folder where to store model checkpoints
DATA_DIR=$EXPERIMENT_ROOT_DIR/t2t_data # path to root folder where to generate training data

BATCH_SIZE=2048
MAX_LEN=150
WARMUP_STEPS=10000
LEARNING_RATE_CONSTANT=1

# decoding (Tensorboard)
BEAM_SIZE=4
ALPHA=0.6

# artificial data part
TOKEN_ERR_PROB="0.15"
TOKEN_ERR_DISTRIBUTION="0.7_0.1_0.1_0.1"
CHAR_ERROR_PROB="0.02"
CHAR_ERR_DISTRIBUTION="0.2_0.2_0.2_0.2_0.2"

LANG="cs"

# technical stuff
NO_EDIT_DATA_DIR=${DATA_DIR}/$PROBLEM-$LANG-tep$TOKEN_ERR_PROB-ted$TOKEN_ERR_DISTRIBUTION-cep$CHAR_ERROR_PROB-ced$CHAR_ERR_DISTRIBUTION
DATA_DIR=${NO_EDIT_DATA_DIR}-${EDIT_WEIGHT}
TRAIN_DIR=${TRAIN_DIR}/$PROBLEM-$LANG-tep$TOKEN_ERR_PROB-ted$TOKEN_ERR_DISTRIBUTION-cep$CHAR_ERROR_PROB-ced$CHAR_ERR_DISTRIBUTION/$MODEL-$MODEL_TYPE-iwdr${INPUT_WORD_DROPOUT_RATE}-twdr${TARGET_WORD_DROPOUT_RATE}-ew${EDIT_WEIGHT}-ws${WARMUP_STEPS}-lrc${LEARNING_RATE_CONSTANT}